const subheaderobj = {
	"1":"TP Cost",
	"2":"Limit Cost",
	"3":"Speed",
	"4":"Acc. (skill)",
	"5":"Acc. (mod)",
	"6":"Field effect",
	"8":"Dmg % (If bound)",
	"11":"Lifesteal %",
	"14":"If front",
	"15":"If back",
	"18":"Swap row on hit (?)",
	"25":"Chase chance red.",
	"45":"Splash %",
	"51":"Min hits (swash)",
	"53":"Target mod",
	"56":"Ailment chance",
	"64":"Damage %",
	"65":"Pincushion dmg",
	"66":"Flat restore",
	"67":"TP restore",
	"68":"HP restore",
	"69":"Self-damage %",
	"73":"Target acts next",
	"75":"Min hits",
	"76":"Max hits",
	"77":"Skill link (ID)",
	"78":"Delayed effect",
	"81":"Poison damage",
	"82":"Charge %",
	"83":"Cure ailment",
	"84":"Cure bind",
	"85":"DMG reduction %",
	"86":"Same row DR bonus",
	"89":"Field steps",
	"121":"DMG Reduction %", //How does this differ from 85?
	"134":"Undodgeable",
	"151":"Act first (knight)",
	"152":"Act first (qdraw)",
	"161":"Provoke flag",
	"170":"Buff duration",
	"172":"Use skill at EOT",
	"174":"Ele %",
	"175":"DEF % (ailment)",
	"176":"Alt % (huh?)",
	"177":"ATK %",
	"178":"Damage taken %",
	"179":"ATK % 2",
	"186":"Max HP %",
	"197":"Evasion",
	"200":"Provoke amount",
	"205":"Ailment immunity", //205 and 206 are, as far as I can tell identical in the game's code
	"206":"Ailment immunity",
	"207":"Bind immunity",
	"216":"Reinforce Flag",
	"219":"Chance to splash",
	"220":"Phys Dmg Up %",
	"221":"Parry Chance",
	"222":"Chance to stun",
	"223":"Phys Def %",
	"226":"Bonus hit chance",
	"230":"Bonus crit chance",
	"239":"Heal mult %", //form qi
	"244":"When ally dies",
	"253":"% health required",
	"274":"Use while defending",
	"279":"Use on dmg skill",
	"280":"Nobility proof flag",
	"282":"Fail if this ailment",
	"295":"Act first",
	"296":"Act last",
	"324":"Sword Dmg %",
	"324":"Sword Dmg %",
	"325":"Club Dmg %",
	"326":"Spear Dmg %",
	"327":"Shield Dmg %",
	"328":"Rapier Dmg %",
	"329":"Gun Dmg %",
	"337":"HP Up %", //note: this subheader doesn't actually change things
	"338":"TP Up %", //nor does this one
	"342":"AGI Up % (unused)",
	"343":"LUC Up % (unused)",
	"344":"Bonus ESC chance",
	"345":"Bonus limit",
	"346":"EXP Bonus % (/10)"
}

const ename = ["Blank","Attack","Claw Cut","Poison Gun","Membrane","Sea God's Anger","Lightning Drop","Panic Rush","Poison Tail","Thorn","100-Leg Bind","Bite Off","Vine Dance","Choke","Chomp","Charge","Crush","Greedy Fang","Sharp Fang","Call Allies","Breath","Jump","Muddle Roar","Defend","Ruin Claw","Ferocious Fish","Decay Breath","Life Absorb","Regen","Power Fang","Cover","Absorb Spirit","Withering Glare","Shell","Foul Spew","Mud Ink","Tear Apart","Aqua Shot","Ruin Fangs","King's Gift","Ice Slurry","Cuff Fangs","Dampen Claw","Claw Chop","Charge In","Ancient Curse","Unload","Combust","Ice Aura","Constricting Leg","Bloody Supper","Poison","Yawn","Twine","Fireball","Crazy Swipe","Mud Spit","Worm Crack","Heavy Fire","Call Allies B","Burning Wind","Fumes","Evil Cry","Flame Claw","Hiss","Ram","Venom Fang","Sticky Acid","Throw","Defend Stance","Throw","Greedy Claws","Predator","Empress Hammer","Duster","Panic Spores","Double Fire","Bide Time","Great Spike","Roar","Lullaby of Rest","Blast Assault","Frost Lap","Fishman Drug","Icicle","Bouha Stance","Rush","Gale Blade","Torpedo","Ice Burn","NONE","Crushing Fang","Ominous Step","Dino Crush","Antihuman Fire","Dis-Element","Zone Icicle","Leaping Slash","Crystal Edge","Nightmare Solo","Soulshaking Song","Dazzling Eye","Bamboo Splicer","Ground Shake","Bronze Fang","Zone Thunder","Zone Blaze","Ice Beast","Wide Cut","Counter","Sea Guillotine","Deadly Incisor","Gel Electrolyte","Sleeper","Petals","Lightning Call","Bullrush","Moon Prayer","Venom","Branch","Stunning Spore","Diving Breath","Silent Claw","Stone Needle","Bolt Spread","Heavenly Bolt","Stinky Mist","Thunderclap","Dozing Gaze","Crazed Shout","Divine Storm","Exhaust Field","Phosphorescence","Amputate","Scythe Dance","Curse Spores","Violent Vines","Tangling Vines","Scorching Hell","Bewildering Eye","Snapping Teeth","Discharge","Crazy Noise","Binding","Mad Charge","Stone Eye","Spirit Dry","Parasite Venom","Dragon Head","Seven Plagues","Halloween","NONE","NONE","NONE","NONE","NONE","Self-Destruct","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","Change","NONE","NONE","NONE","NONE","NONE","NONE","Spurting Fumes","Kaishaku Heal","NONE","NONE","NONE","Imperial Pride","NONE","NONE","Counter","NONE","NONE","NONE","NONE","NONE","Crystal Edge","Reversal Spore","NONE","NONE","NONE (poison damage handler?)","NONE","Counter","Mud Throw","Fin Smack","Whip Ripper","Earthquake","Marsh Dive","Submerged Move","Escape","Grand Berry","Ocean Rave","Spout","Great Melody","Freeze Ripple","Souha Stance","Tenchi Souha Sho","Disperse","Focus","Line Slice","Punching","Iron Claw","Heat Ray","Blizzard Breath","Electric Flash","Malfunction","Lament","Dubious Mist","Thin Ice","Thunder Wrath","Ocean Drop","Sweet Song","Brandish","Grasp Arm","Liberation","Uzurai","Punishment","Dark Breath","Thorn Cutter","Vine Rush","Spine Blaze","Frozen Eye","Death Thunder","Liberate","Accumulate","Bite Off","Shark Rush","Evil Placoid","Charge","Baracuda","Heated Shot","Dazzling Aurora","Arrest Mine","Oil Cannon","Thunder Cannon","Thunder Feather","Godly Flash","Panic Claw","Ice Crush","Heavenly Light","Critical Break","Fuming Snort","Fumes","Tie Up","Overeat","Hard Scale","Cold Wave","NONE","Violent Grudge","Withstand","NONE","Tentacle Grab","Cnidocyte Rush","Tentacle Reap","Tentacle Suck","Twin Ice Spear","Ice Breath","Ice Pillar","Twin Fire Spear","Fire Breath","Fire Pillar","Twin Volt Spear","Volt Breath","Volt Pillar","Dragon Quake","Ultimate Ruin","Regenerate","Devilish Smile","Misfortune","Breath of Envy","Mist Robe","Cold Stare","Demon Kiss","Reflection","Multi Hammer","Triple Hammer","Death Tentacle","Squid Press","Tidal Wave","Shower","Restoration","Supernova","Black Fire","Scarlet Ice","Green Flash","Grand Dive","Wing Rush","Ancient Breath","NONE","Magma Ocean","Ice Tempest","Proton Thunder","Regenerator","NONE","NONE","NONE","NONE","Nameless Wall","Mist Curtain","Chaotic Beckon","Spurting Fumes","Abyssal Offering","NONE","Demon Rage","Rising Claw","Chaos Tentacle","Primitive Burn","Foul Glacier","Dark Lightning","Ripping Neigh","Fetter Dance","Tail Swing","Divine Wrath","Retribution","Imperial Pride","Summons","Fortress","Conciliate","Restraint","Cruel Stare","Cruelty","Demon Reaper","Falcon Thrust","War Spirit","Kaitou Ranma","Ouka no Mai","Frigid","Regen","Iceblock","NONE","NONE","Zero Point","Shower","NONE","NONE","NONEDATA","NONE","Regen","Magic Lullaby","Petrivoice","Darkness Coil","Poison Tale","Voltage","Curse","Corrupt","Fangs","Blow","Searing","Howling","NO DATA","Beat","Red Fang","Strike","Aquaveil","Flood","Coiling","Ice Gaze","Frost Smile","Shock","Tentacle Beat","Vampire Kiss","Pollen","Cry Soul","Embrace","Lullaby","Tentacle","Six Sins","NO DATA","NO DATA","NO DATA","Corroding Acid","Lay Egg","Swallow Whole","Phoenix","Multiply","Multiply","Multiply","Poison Seeds","Scream","Poison Spores","Self-Destruct 1","Palsy Destruct","Endure"]; //it's gross but there's really no reason to load it as a data file tbh

const pname = ["Blank","Attack","HP Up","TP Up","Bandage","Combat Study","Limit Boost","AGI Up","LUC Up","Esc Up","Limit Boost","Chop","Mine","Take","Royal Lineage","Monarch March","Royal Veil","Triumphant Cry","Reinforce","Nobility Proof","Attack Order","Guard Order","Rally Order","Negotiation","Inspire","Ad Nihilo","Fire Arms","Freeze Arms","Shock Arms","Regal Radiance","Prevent Order","Protect Order","Knighthood","Endless Battle","Sword Mastery","Club Mastery","Avenger","Stun Attack","Wild Swings","Charge","Berserker Vow","Wolf Howl","White Flame","Break","Rush","Bind Cut","Rampage","Blade Rave","Crushing Blow","Arm Breaker","Freezing Blow","Nine Smashes","Guardian","Spear Mastery","Shield Mastery","Parry","Magic Parry","Recuperate","Selflessness","Provoke","Shrug Off","Switch Stab","Blitzritter","Long Stride","Line Guard","Antifire","Anticold","Antivolt","Bodyguard","Overwatch","Vigilance","Trickster","Rapier Mastery","Gun Mastery","Swashbuckling","Lady Luck","Limit Boost","Eagle Eye","Quick Draw","Rapid Fire","Chase Flame","Chase Ice","Chase Volt","Lights Out","Hanging","Chase Saber","Chase Blow","Chase Thrust","Pincushion","Troublemaker","Keburi no Sue","Kubikiri","Senpuku","Karuwaza","Nikudan","Knife Mastery","Suikyou","Otori","Kumogakure","Bunshin","Makibishi","Kagerou","Sarutobi","Fukubari","Kagenui","Takanoha","Izuna","Tagen Battou","Tonsou Jutsu","Form Qi","Fist Mastery","Ascetic Deeds","Ascetic Reward","Blood Return","Waking Chakra","Kikouken","Healing","Party Heal","Full Heal","Counter","Retaliate","Refresh","Resurrect","Unbind","Line Heal","Breakfire Fist","Darkness Fist","Fire Walk","Ether Mastery","Fire Mastery","Ice Mastery","Volt Mastery","Etheric Return","Singularity","Etheric Charge","Dark Ether","Meteor","Fire Star","Binary Fire","Fire Prophecy","Ice Star","Binary Ice","Ice Prophecy","Volt Star","Binary Thunder","Volt Prophecy","Horoscope","Beast Soul","Wild Mastery","Nature Pact","Sacrifice 1","Sacrifice 2","Alertness","Beast Roar","Primal Drums","Dismiss Beast","Call Bird","Call Snake","Call Mole","Call Insect","Call Cow","Call Owl","Call Elephant","Call Tiger","Call Lion","Call Ooze","Giant Kill","Bolt Mastery","Extend","Night Vision","Double Action","Proper Form","Pop Flares","Smoke Grenade","Snipe","Heavy Shot","Strafe","Sharpshooter","Armor Piercer","Fire Barrage","Front Mortar","Ice Barrage","Volt Barrage","Cloudbuster","Ambush","Earth's Bounty","Persistence","Brave Heart","Camp Mastery","Waste Not","Keen Nose","Play Possum","Sympathy Pain","Rotten Egg","Lullaby","Strange Seeds","Slap Awake","Horseplay","Double Crop","Safe Stroll","To Market","Rain or Shine","Keen Eye","Harvestry","Second Sword","Katana Mastery","Endure","Kaishaku","Bloody Lance","Morale Boost","Unified Spirit","Hilt Strike","Myoujou","Magatoki","5-Ring Sword","Daifuhensha","Warrior Might","Fore Honor","Rear Dignity","Ambush Stance","Fusillade","Blitz Command","Retreat","Sleep Mode","Overheat","Virus Scanner","EM Barrier","Infravision","Data Mining","Red Bot","Blue Bot","Yellow Bot","Resupply","Reflector","Shoot","All Out","Rocket Punch","Rocket Head","Rocket Jump","HP Cannon","Core Dump","Defrag","Cross Slash","Indomitable","Charge Tactic","Mumyouken","Guard Tactic","Second Wind","Lethal Tactic","Aegis Defense","Hellfire","Wind Tactic","Absolute Zero","Aegis Barrier","Sungrazer","Regroup Tactic","Typhoon Bolt","Aegis Shield","Quintessence","Star Smasher","Lucky Hammer","Uroboros Guard","Immortal","Buc Farm","Buc Nin","Buc Mon","Buc Farm","Nin Prin","Nin Glad","Nin Farm","Nin Do","Nin Farm","Bind Feather","Wind Wrap","Scratch","Poison Dust","Bull Run","Sleep Powder","Reckless Rush","Death Fang","Sleeping Lion","Plague Gunk","Bind Feather","Wind Wrap","Scratch","Poison Dust","Bull Run","Sleep Powder","Reckless Rush","Fierce Counter","Regal Authority","Plague Gunk","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","Fusillade","Blitz Command","NONE","Reflector","EM Barrier","Kaishaku","NONE","NONE","NONE","Zod Nin","Zod Aba","Buc Nin","Buc Farm","Nin Prin","Snipe","Sharpshooter","NONE","NONE","NONE","NONE","NONE","NONE","NONE","NONE","Medica Type","Amrita Type","Hamao Type","Nectar Type","Nectar Type","Soma Type","Theriaca A","Theriaca A","Theriaca B","Theriaca B","NONE","NONE","NONE","Discharge","NONE","NONE","Strange Seed","Tiger Counter","Warrior Might","Cloudbuster","Counter","Retaliate","Chase Saber","Chase Blow","Chase Thrust","Chase Flame","Chase Ice","Chase Volt","Makibishi","Ambush Stance","Rocket Puch","Rocket Headbutt","Rocket Jump","Red Module","Blue Module","Yellow Module","Fire All","Infect","Restore Mark","Fire Prophecy","Ice Prophecy","Volt Prophecy","Last Chase","Metapon","Unihorn","Bravant","Stonard","Fire Mist","Ice Mist","Volt Mist","Cut Mist","Bash Mist","Stab Mist","Blaze Oil","Freeze Oil","Shock Oil","Fire Jar","Flame Jar","Ice Jar","Frost Jar","Volt Jar","Storm Jar","Poison Gas","Stun Gas","Blind Gas","Sleep Gas","Curse Gas","Addle Gas"]

const textheaders = ["Max level","Skill type","Body part","TValidity","Target","TarGroup","Where Use","Buff/Debuff","B/D type","unk.","B/D element","Dmg element","ACureorInf","Ailment","Skill fl","unk3"]; //I don't like this. I should rewrite it as an object probably

const errorm = ["No error. Why are you here?","Error! ID must be under 400 for enemy table.","Error! ID must be under 421 for player table.","Error! Must enter a number.","Error! Skill table size mismatched. This should never happen."]; //same with this